# Apply label "feature" if head matches "feature/*"
feature:
  head: "feature/*"

# Apply label "feature" if head matches "improvement/*"
improvement:
  head: "improvement/*"
 
# Apply label "feature" if head matches "bug/*"
bug:
  head: "bug/*"
 
